"""
Entity weights and categories for OpenLabels.

Defines sensitivity weights (1-10) and categories for all entity types.
This is the source of truth for entity risk scoring.
"""

from typing import Dict


# =============================================================================
# ENTITY WEIGHTS (1-10 scale per spec)
# =============================================================================

ENTITY_WEIGHTS: Dict[str, int] = {
    # =========================================================================
    # DIRECT IDENTIFIERS (8-10)
    # =========================================================================
    "SSN": 10,
    "PASSPORT": 10,
    "DRIVERS_LICENSE": 7,
    "STATE_ID": 7,
    "TAX_ID": 8,
    "AADHAAR": 10,
    "NHS_NUMBER": 8,
    "MEDICARE_ID": 8,
    "MBI": 8,
    "HICN": 8,

    # =========================================================================
    # HEALTHCARE / PHI (5-8)
    # =========================================================================
    "MRN": 8,
    "HEALTH_PLAN_ID": 8,
    "NPI": 7,
    "DEA": 7,
    "DIAGNOSIS": 8,
    "MEDICATION": 6,
    "LAB_TEST": 5,
    "ENCOUNTER_ID": 5,
    "ACCESSION_ID": 5,
    "PHARMACY_ID": 5,
    "PATIENT_ACCOUNT": 6,
    "DATE_MEDICAL": 3,
    "PAYER": 2,
    "ROOM": 2,
    "MEDICAL_LICENSE": 5,

    # =========================================================================
    # PERSONAL INFORMATION (2-8)
    # =========================================================================
    "NAME": 5,
    "NAME_PATIENT": 8,
    "NAME_PROVIDER": 4,
    "NAME_RELATIVE": 7,
    "DATE_DOB": 6,
    "DOB": 6,
    "DATE": 3,
    "TIME": 2,
    "DATETIME": 3,
    "AGE": 4,
    "GENDER": 2,
    "RACE_ETHNICITY": 4,
    "ETHNICITY": 4,
    "RELIGION": 4,
    "SEXUAL_ORIENTATION": 5,
    "EMPLOYER": 4,
    "PROFESSION": 3,
    "EMPLOYEE_ID": 5,

    # =========================================================================
    # CONTACT INFORMATION (2-5)
    # =========================================================================
    "EMAIL": 5,
    "PHONE": 4,
    "ADDRESS": 5,
    "ZIP": 3,
    "CITY": 2,
    "STATE": 2,
    "LOCATION": 3,
    "FACILITY": 4,

    # =========================================================================
    # FINANCIAL (5-10)
    # =========================================================================
    "CREDIT_CARD": 10,
    "BANK_ACCOUNT": 7,
    "BANK_ROUTING": 6,
    "IBAN": 7,
    "SWIFT_BIC": 5,
    # Securities
    "CUSIP": 5,
    "ISIN": 5,
    "SEDOL": 5,
    "FIGI": 5,
    "LEI": 5,
    # Crypto
    "BITCOIN_ADDRESS": 8,
    "ETHEREUM_ADDRESS": 8,
    "CRYPTO_SEED_PHRASE": 10,
    "SOLANA_ADDRESS": 8,
    "CARDANO_ADDRESS": 8,
    "LITECOIN_ADDRESS": 8,
    "DOGECOIN_ADDRESS": 8,
    "XRP_ADDRESS": 8,

    # =========================================================================
    # DIGITAL IDENTIFIERS (2-6)
    # =========================================================================
    "IP_ADDRESS": 4,
    "MAC_ADDRESS": 4,
    "URL": 3,
    "USERNAME": 5,
    "DEVICE_ID": 5,
    "IMEI": 6,
    "VIN": 5,
    "BIOMETRIC_ID": 8,
    "IMAGE_ID": 4,
    "TRACKING_NUMBER": 2,

    # =========================================================================
    # CREDENTIALS & SECRETS (8-10)
    # =========================================================================
    "PASSWORD": 10,
    "API_KEY": 10,
    "SECRET": 10,
    "PRIVATE_KEY": 10,
    "JWT": 8,
    "BASIC_AUTH": 10,
    "BEARER_TOKEN": 8,
    "DATABASE_URL": 10,

    # Cloud Provider Credentials
    "AWS_ACCESS_KEY": 10,
    "AWS_SECRET_KEY": 10,
    "AWS_SESSION_TOKEN": 10,
    "AZURE_STORAGE_KEY": 10,
    "AZURE_CONNECTION_STRING": 10,
    "AZURE_SAS_TOKEN": 8,
    "GOOGLE_API_KEY": 10,
    "GOOGLE_OAUTH_ID": 6,
    "GOOGLE_OAUTH_SECRET": 10,
    "FIREBASE_KEY": 10,
    "GCP_CREDENTIALS": 10,
    "GCP_SERVICE_ACCOUNT": 10,
    "GCP_API_KEY": 10,
    "DIGITALOCEAN_TOKEN": 10,
    "LINODE_TOKEN": 10,
    "VULTR_API_KEY": 10,
    "ALIBABA_ACCESS_KEY": 10,
    "ORACLE_CLOUD_KEY": 10,
    "IBM_CLOUD_KEY": 10,
    "CLOUDFLARE_API_KEY": 10,
    "CLOUDFLARE_TOKEN": 10,

    # AI/ML Platform Keys
    "OPENAI_API_KEY": 10,
    "ANTHROPIC_API_KEY": 10,
    "HUGGINGFACE_TOKEN": 10,
    "COHERE_API_KEY": 10,
    "REPLICATE_TOKEN": 10,
    "STABILITY_API_KEY": 10,
    "MISTRAL_API_KEY": 10,
    "TOGETHER_API_KEY": 10,
    "GROQ_API_KEY": 10,

    # CI/CD Platform Tokens
    "CIRCLECI_TOKEN": 10,
    "TRAVIS_TOKEN": 10,
    "JENKINS_TOKEN": 10,
    "AZURE_DEVOPS_PAT": 10,
    "BITBUCKET_TOKEN": 10,
    "VERCEL_TOKEN": 10,
    "NETLIFY_TOKEN": 10,
    "RENDER_API_KEY": 10,
    "RAILWAY_TOKEN": 10,
    "FLY_TOKEN": 10,

    # Container Registry Tokens
    "DOCKER_HUB_TOKEN": 10,
    "QUAY_TOKEN": 10,
    "ECR_TOKEN": 10,
    "GCR_TOKEN": 10,
    "ACR_TOKEN": 10,
    "HARBOR_TOKEN": 10,

    # Communication Platform Tokens
    "TELEGRAM_BOT_TOKEN": 10,
    "TEAMS_WEBHOOK": 8,
    "ZOOM_JWT": 10,
    "WEBEX_TOKEN": 10,
    "TWITCH_TOKEN": 10,
    "WHATSAPP_TOKEN": 10,

    # Payment Processor Tokens
    "PAYPAL_CLIENT_ID": 8,
    "PAYPAL_SECRET": 10,
    "BRAINTREE_TOKEN": 10,
    "PLAID_CLIENT_ID": 8,
    "PLAID_SECRET": 10,
    "ADYEN_API_KEY": 10,
    "KLARNA_TOKEN": 10,

    # SaaS API Tokens
    "ATLASSIAN_TOKEN": 10,
    "NOTION_TOKEN": 10,
    "AIRTABLE_KEY": 10,
    "LINEAR_TOKEN": 10,
    "FIGMA_TOKEN": 10,
    "ASANA_TOKEN": 10,
    "MONDAY_TOKEN": 10,
    "ZENDESK_TOKEN": 10,
    "INTERCOM_TOKEN": 10,
    "SEGMENT_KEY": 10,
    "MIXPANEL_TOKEN": 8,
    "AMPLITUDE_KEY": 8,
    "LAUNCHDARKLY_KEY": 10,
    "SENTRY_DSN": 8,
    "PAGERDUTY_KEY": 10,
    "OPSGENIE_KEY": 10,
    "ROLLBAR_TOKEN": 8,

    # Database & Data Platform Tokens
    "SUPABASE_KEY": 10,
    "PLANETSCALE_TOKEN": 10,
    "NEON_TOKEN": 10,
    "COCKROACHDB_TOKEN": 10,
    "SNOWFLAKE_TOKEN": 10,
    "DATABRICKS_TOKEN": 10,
    "ELASTICSEARCH_KEY": 10,
    "ALGOLIA_KEY": 10,
    "REDIS_URL": 10,
    "GRAFANA_TOKEN": 10,

    # Email Service Tokens
    "POSTMARK_TOKEN": 10,
    "MAILGUN_KEY": 10,
    "RESEND_KEY": 10,
    "SPARKPOST_KEY": 10,
    "SES_CREDENTIALS": 10,

    # SMS/Voice Service Tokens
    "VONAGE_KEY": 10,
    "VONAGE_SECRET": 10,
    "PLIVO_AUTH_ID": 8,
    "PLIVO_TOKEN": 10,
    "MESSAGEBIRD_KEY": 10,
    "BANDWIDTH_TOKEN": 10,

    # Legacy Service Provider Tokens
    "GITHUB_TOKEN": 10,
    "GITLAB_TOKEN": 10,
    "SLACK_TOKEN": 10,
    "SLACK_WEBHOOK": 8,
    "DISCORD_TOKEN": 10,
    "DISCORD_WEBHOOK": 7,
    "STRIPE_KEY": 10,
    "TWILIO_ACCOUNT_SID": 7,
    "TWILIO_KEY": 10,
    "TWILIO_TOKEN": 10,
    "SENDGRID_KEY": 10,
    "MAILCHIMP_KEY": 8,
    "SQUARE_TOKEN": 10,
    "SQUARE_SECRET": 10,
    "SHOPIFY_TOKEN": 10,
    "SHOPIFY_KEY": 8,
    "SHOPIFY_SECRET": 10,
    "HEROKU_KEY": 10,
    "DATADOG_KEY": 8,
    "NEWRELIC_KEY": 8,
    "NPM_TOKEN": 10,
    "PYPI_TOKEN": 10,
    "NUGET_KEY": 8,

    # =========================================================================
    # GOVERNMENT & CLASSIFICATION (4-10)
    # =========================================================================
    "CLASSIFICATION_LEVEL": 8,
    "CLASSIFICATION_MARKING": 10,
    "SCI_MARKING": 10,
    "DISSEMINATION_CONTROL": 8,
    "CLEARANCE_LEVEL": 7,
    "ITAR_MARKING": 8,
    "EAR_MARKING": 7,
    "CAGE_CODE": 4,
    "DUNS_NUMBER": 4,
    "UEI": 4,
    "DOD_CONTRACT": 5,
    "GSA_CONTRACT": 4,

    # =========================================================================
    # EDUCATION / FERPA (5-8)
    # =========================================================================
    "STUDENT_ID": 7,
    "TRANSCRIPT": 7,
    "ENROLLMENT_ID": 6,
    "FINANCIAL_AID_ID": 7,
    "SCHOOL_RECORD": 6,
    "GPA": 5,
    "DISCIPLINARY_RECORD": 7,
    "IEP_ID": 8,
    "TEACHER_ID": 5,
    "FERPA_DIRECTORY_INFO": 4,

    # =========================================================================
    # LEGAL (4-8)
    # =========================================================================
    "CASE_NUMBER": 6,
    "BAR_NUMBER": 5,
    "COURT_ID": 4,
    "PACER_ID": 6,
    "INMATE_NUMBER": 7,
    "PROBATION_ID": 7,
    "ARREST_RECORD": 8,
    "WARRANT_NUMBER": 7,
    "JUDGMENT_ID": 6,
    "LEGAL_HOLD_ID": 5,

    # =========================================================================
    # VEHICLE & TRANSPORTATION (4-7)
    # =========================================================================
    "LICENSE_PLATE": 5,
    "REGISTRATION_NUMBER": 5,
    "TITLE_NUMBER": 5,
    "DOT_NUMBER": 4,
    "MC_NUMBER": 4,
    "VESSEL_ID": 5,
    "AIRCRAFT_TAIL": 5,
    "PILOT_LICENSE": 6,
    "CDL_NUMBER": 7,
    "TOLL_ACCOUNT": 4,

    # =========================================================================
    # IMMIGRATION (6-10)
    # =========================================================================
    "A_NUMBER": 10,
    "VISA_NUMBER": 8,
    "I94_NUMBER": 8,
    "GREEN_CARD_NUMBER": 10,
    "EAD_NUMBER": 8,
    "SEVIS_ID": 7,
    "TRAVEL_DOCUMENT_NUMBER": 8,
    "PETITION_NUMBER": 6,
    "NATURALIZATION_NUMBER": 8,

    # =========================================================================
    # INSURANCE (3-7)
    # =========================================================================
    "POLICY_NUMBER": 6,
    "CLAIM_NUMBER": 6,
    "AGENT_NUMBER": 4,
    "ADJUSTER_ID": 4,
    "NAIC_NUMBER": 3,
    "AUTO_POLICY_ID": 6,
    "HOME_POLICY_ID": 6,
    "LIFE_POLICY_ID": 7,
    "WORKERS_COMP_CLAIM": 7,
    "DISABILITY_CLAIM_ID": 7,

    # =========================================================================
    # REAL ESTATE (3-7)
    # =========================================================================
    "PARCEL_NUMBER": 4,
    "DEED_NUMBER": 5,
    "MORTGAGE_ACCOUNT": 7,
    "ESCROW_NUMBER": 6,
    "MLS_NUMBER": 3,
    "HOA_ACCOUNT": 4,
    "TITLE_POLICY_NUMBER": 5,
    "PROPERTY_TAX_ID": 4,

    # =========================================================================
    # TELECOMMUNICATIONS (4-7)
    # =========================================================================
    "IMSI": 7,
    "ICCID": 6,
    "MSISDN": 6,
    "MEID": 6,
    "ESN": 5,
    "CARRIER_ACCOUNT": 5,
    "VOIP_ACCOUNT": 4,
    "CALLING_CARD_NUMBER": 5,
    "PORT_NUMBER": 4,

    # =========================================================================
    # BIOMETRIC & GENETIC (7-10)
    # =========================================================================
    "FINGERPRINT_TEMPLATE": 10,
    "FACE_TEMPLATE": 10,
    "IRIS_TEMPLATE": 10,
    "VOICE_PRINT": 8,
    "RETINAL_SCAN": 10,
    "PALM_PRINT": 8,
    "GAIT_SIGNATURE": 7,
    "DNA_SEQUENCE": 10,
    "GENETIC_MARKER": 10,
    "ANCESTRY_ID": 7,
    "BIOBANK_ID": 8,

    # =========================================================================
    # MILITARY (3-10)
    # =========================================================================
    "EDIPI": 8,
    "SERVICE_NUMBER": 8,
    "MILITARY_ID": 8,
    "VA_CLAIM_NUMBER": 7,
    "DD214_NUMBER": 8,
    "MOS_CODE": 3,
    "UNIT_IDENTIFICATION": 4,
    "SECURITY_BADGE_ID": 6,
    "SIPR_TOKEN": 10,
    "CAC_PIN": 10,

    # =========================================================================
    # SENSITIVE FILES & CONTEXT (6-10)
    # =========================================================================
    "DOTENV_FILE": 10,
    "KUBECONFIG": 10,
    "SSH_CONFIG": 8,
    "DOCKER_CONFIG": 8,
    "NPM_RC": 10,
    "PYPIRC": 10,
    "AWS_CREDENTIALS_FILE": 10,
    "NETRC": 10,
    "HTPASSWD": 8,
    "PGP_PRIVATE": 10,
    "TERRAFORM_STATE": 10,
    "ANSIBLE_VAULT": 8,
    "CERTIFICATE_BUNDLE": 7,
    "KEYSTORE": 10,
    "WALLET_FILE": 10,
    "HISTORY_FILE": 6,
    "SHADOW_FILE": 10,

    # =========================================================================
    # INTERNATIONAL IDs (7-10)
    # =========================================================================
    "SIN_CA": 10,
    "NINO_UK": 8,
    "UTR_UK": 8,
    "INSEE_FR": 8,
    "PERSONALAUSWEIS_DE": 8,
    "CODICE_FISCALE_IT": 8,
    "DNI_ES": 8,
    "CPF_BR": 10,
    "RG_BR": 8,
    "CURP_MX": 8,
    "AADHAAR_IN": 10,
    "PAN_IN": 8,
    "TFN_AU": 8,
    "MY_NRIC": 8,
    "CHINA_RESIDENT_ID": 10,
    "JAPAN_MY_NUMBER": 10,

    # =========================================================================
    # MISCELLANEOUS
    # =========================================================================
    "UNIQUE_ID": 5,
}

# Default weight for unknown entity types
DEFAULT_WEIGHT = 5


# =============================================================================
# ENTITY CATEGORIES (for co-occurrence rules)
# =============================================================================

ENTITY_CATEGORIES: Dict[str, str] = {
    # Direct identifiers
    "SSN": "direct_identifier",
    "PASSPORT": "direct_identifier",
    "DRIVERS_LICENSE": "direct_identifier",
    "STATE_ID": "direct_identifier",
    "TAX_ID": "direct_identifier",
    "AADHAAR": "direct_identifier",
    "AADHAAR_IN": "direct_identifier",
    "A_NUMBER": "direct_identifier",
    "GREEN_CARD_NUMBER": "direct_identifier",
    "VISA_NUMBER": "direct_identifier",
    "I94_NUMBER": "direct_identifier",
    "EAD_NUMBER": "direct_identifier",
    "NATURALIZATION_NUMBER": "direct_identifier",
    "SIN_CA": "direct_identifier",
    "NINO_UK": "direct_identifier",
    "UTR_UK": "direct_identifier",
    "INSEE_FR": "direct_identifier",
    "PERSONALAUSWEIS_DE": "direct_identifier",
    "CODICE_FISCALE_IT": "direct_identifier",
    "DNI_ES": "direct_identifier",
    "CPF_BR": "direct_identifier",
    "RG_BR": "direct_identifier",
    "CURP_MX": "direct_identifier",
    "PAN_IN": "direct_identifier",
    "TFN_AU": "direct_identifier",
    "MY_NRIC": "direct_identifier",
    "CHINA_RESIDENT_ID": "direct_identifier",
    "JAPAN_MY_NUMBER": "direct_identifier",
    "MEDICARE_ID": "direct_identifier",

    # Healthcare / PHI
    "MRN": "health_info",
    "HEALTH_PLAN_ID": "health_info",
    "NPI": "health_info",
    "DEA": "health_info",
    "DIAGNOSIS": "health_info",
    "MEDICATION": "health_info",
    "LAB_TEST": "health_info",
    "ENCOUNTER_ID": "health_info",
    "ACCESSION_ID": "health_info",
    "PHARMACY_ID": "health_info",
    "PATIENT_ACCOUNT": "health_info",
    "DATE_MEDICAL": "health_info",
    "MBI": "health_info",
    "HICN": "health_info",
    "NHS_NUMBER": "health_info",
    "NAME_PATIENT": "health_info",
    "NAME_PROVIDER": "health_info",
    "PAYER": "health_info",
    "ROOM": "health_info",
    "MEDICAL_LICENSE": "health_info",

    # Financial
    "CREDIT_CARD": "financial",
    "BANK_ACCOUNT": "financial",
    "BANK_ROUTING": "financial",
    "IBAN": "financial",
    "SWIFT_BIC": "financial",
    "CUSIP": "financial",
    "ISIN": "financial",
    "SEDOL": "financial",
    "FIGI": "financial",
    "LEI": "financial",
    "BITCOIN_ADDRESS": "financial",
    "ETHEREUM_ADDRESS": "financial",
    "CRYPTO_SEED_PHRASE": "financial",
    "SOLANA_ADDRESS": "financial",
    "CARDANO_ADDRESS": "financial",
    "LITECOIN_ADDRESS": "financial",
    "DOGECOIN_ADDRESS": "financial",
    "XRP_ADDRESS": "financial",
    "MORTGAGE_ACCOUNT": "financial",

    # Contact
    "EMAIL": "contact",
    "PHONE": "contact",
    "ADDRESS": "contact",
    "ZIP": "contact",
    "CITY": "contact",
    "STATE": "contact",
    "LOCATION": "contact",
    "FACILITY": "contact",
    "URL": "contact",

    # Quasi-identifiers
    "NAME": "quasi_identifier",
    "NAME_RELATIVE": "quasi_identifier",
    "DATE_DOB": "quasi_identifier",
    "DOB": "quasi_identifier",
    "DATE": "quasi_identifier",
    "TIME": "quasi_identifier",
    "DATETIME": "quasi_identifier",
    "AGE": "quasi_identifier",
    "GENDER": "quasi_identifier",
    "RACE_ETHNICITY": "quasi_identifier",
    "ETHNICITY": "quasi_identifier",
    "RELIGION": "quasi_identifier",
    "SEXUAL_ORIENTATION": "quasi_identifier",
    "EMPLOYER": "quasi_identifier",
    "PROFESSION": "quasi_identifier",
    "EMPLOYEE_ID": "quasi_identifier",

    # Digital identifiers
    "IP_ADDRESS": "digital_identifier",
    "MAC_ADDRESS": "digital_identifier",
    "DEVICE_ID": "digital_identifier",
    "IMEI": "digital_identifier",
    "USERNAME": "digital_identifier",
    "VIN": "digital_identifier",
    "BIOMETRIC_ID": "digital_identifier",
    "IMAGE_ID": "digital_identifier",
    "TRACKING_NUMBER": "digital_identifier",
    "LICENSE_PLATE": "digital_identifier",
    "IMSI": "digital_identifier",
    "ICCID": "digital_identifier",
    "MSISDN": "digital_identifier",
    "MEID": "digital_identifier",
    "ESN": "digital_identifier",

    # Credentials (all credential types)
    "PASSWORD": "credential",
    "API_KEY": "credential",
    "SECRET": "credential",
    "PRIVATE_KEY": "credential",
    "JWT": "credential",
    "BASIC_AUTH": "credential",
    "BEARER_TOKEN": "credential",
    "DATABASE_URL": "credential",
    "AWS_ACCESS_KEY": "credential",
    "AWS_SECRET_KEY": "credential",
    "AWS_SESSION_TOKEN": "credential",
    "AZURE_STORAGE_KEY": "credential",
    "AZURE_CONNECTION_STRING": "credential",
    "AZURE_SAS_TOKEN": "credential",
    "GOOGLE_API_KEY": "credential",
    "GOOGLE_OAUTH_ID": "credential",
    "GOOGLE_OAUTH_SECRET": "credential",
    "FIREBASE_KEY": "credential",
    "GCP_CREDENTIALS": "credential",
    "GCP_SERVICE_ACCOUNT": "credential",
    "GCP_API_KEY": "credential",
    "DIGITALOCEAN_TOKEN": "credential",
    "LINODE_TOKEN": "credential",
    "VULTR_API_KEY": "credential",
    "ALIBABA_ACCESS_KEY": "credential",
    "ORACLE_CLOUD_KEY": "credential",
    "IBM_CLOUD_KEY": "credential",
    "CLOUDFLARE_API_KEY": "credential",
    "CLOUDFLARE_TOKEN": "credential",
    "OPENAI_API_KEY": "credential",
    "ANTHROPIC_API_KEY": "credential",
    "HUGGINGFACE_TOKEN": "credential",
    "COHERE_API_KEY": "credential",
    "REPLICATE_TOKEN": "credential",
    "STABILITY_API_KEY": "credential",
    "MISTRAL_API_KEY": "credential",
    "TOGETHER_API_KEY": "credential",
    "GROQ_API_KEY": "credential",
    "CIRCLECI_TOKEN": "credential",
    "TRAVIS_TOKEN": "credential",
    "JENKINS_TOKEN": "credential",
    "AZURE_DEVOPS_PAT": "credential",
    "BITBUCKET_TOKEN": "credential",
    "VERCEL_TOKEN": "credential",
    "NETLIFY_TOKEN": "credential",
    "RENDER_API_KEY": "credential",
    "RAILWAY_TOKEN": "credential",
    "FLY_TOKEN": "credential",
    "DOCKER_HUB_TOKEN": "credential",
    "QUAY_TOKEN": "credential",
    "ECR_TOKEN": "credential",
    "GCR_TOKEN": "credential",
    "ACR_TOKEN": "credential",
    "HARBOR_TOKEN": "credential",
    "TELEGRAM_BOT_TOKEN": "credential",
    "TEAMS_WEBHOOK": "credential",
    "ZOOM_JWT": "credential",
    "WEBEX_TOKEN": "credential",
    "TWITCH_TOKEN": "credential",
    "WHATSAPP_TOKEN": "credential",
    "PAYPAL_CLIENT_ID": "credential",
    "PAYPAL_SECRET": "credential",
    "BRAINTREE_TOKEN": "credential",
    "PLAID_CLIENT_ID": "credential",
    "PLAID_SECRET": "credential",
    "ADYEN_API_KEY": "credential",
    "KLARNA_TOKEN": "credential",
    "ATLASSIAN_TOKEN": "credential",
    "NOTION_TOKEN": "credential",
    "AIRTABLE_KEY": "credential",
    "LINEAR_TOKEN": "credential",
    "FIGMA_TOKEN": "credential",
    "ASANA_TOKEN": "credential",
    "MONDAY_TOKEN": "credential",
    "ZENDESK_TOKEN": "credential",
    "INTERCOM_TOKEN": "credential",
    "SEGMENT_KEY": "credential",
    "MIXPANEL_TOKEN": "credential",
    "AMPLITUDE_KEY": "credential",
    "LAUNCHDARKLY_KEY": "credential",
    "SENTRY_DSN": "credential",
    "PAGERDUTY_KEY": "credential",
    "OPSGENIE_KEY": "credential",
    "ROLLBAR_TOKEN": "credential",
    "SUPABASE_KEY": "credential",
    "PLANETSCALE_TOKEN": "credential",
    "NEON_TOKEN": "credential",
    "COCKROACHDB_TOKEN": "credential",
    "SNOWFLAKE_TOKEN": "credential",
    "DATABRICKS_TOKEN": "credential",
    "ELASTICSEARCH_KEY": "credential",
    "ALGOLIA_KEY": "credential",
    "REDIS_URL": "credential",
    "GRAFANA_TOKEN": "credential",
    "POSTMARK_TOKEN": "credential",
    "MAILGUN_KEY": "credential",
    "RESEND_KEY": "credential",
    "SPARKPOST_KEY": "credential",
    "SES_CREDENTIALS": "credential",
    "VONAGE_KEY": "credential",
    "VONAGE_SECRET": "credential",
    "PLIVO_AUTH_ID": "credential",
    "PLIVO_TOKEN": "credential",
    "MESSAGEBIRD_KEY": "credential",
    "BANDWIDTH_TOKEN": "credential",
    "GITHUB_TOKEN": "credential",
    "GITLAB_TOKEN": "credential",
    "SLACK_TOKEN": "credential",
    "SLACK_WEBHOOK": "credential",
    "DISCORD_TOKEN": "credential",
    "DISCORD_WEBHOOK": "credential",
    "STRIPE_KEY": "credential",
    "TWILIO_ACCOUNT_SID": "credential",
    "TWILIO_KEY": "credential",
    "TWILIO_TOKEN": "credential",
    "SENDGRID_KEY": "credential",
    "MAILCHIMP_KEY": "credential",
    "SQUARE_TOKEN": "credential",
    "SQUARE_SECRET": "credential",
    "SHOPIFY_TOKEN": "credential",
    "SHOPIFY_KEY": "credential",
    "SHOPIFY_SECRET": "credential",
    "HEROKU_KEY": "credential",
    "DATADOG_KEY": "credential",
    "NEWRELIC_KEY": "credential",
    "NPM_TOKEN": "credential",
    "PYPI_TOKEN": "credential",
    "NUGET_KEY": "credential",

    # Classification / Government
    "CLASSIFICATION_LEVEL": "classification_marking",
    "CLASSIFICATION_MARKING": "classification_marking",
    "SCI_MARKING": "classification_marking",
    "DISSEMINATION_CONTROL": "classification_marking",
    "CLEARANCE_LEVEL": "classification_marking",
    "ITAR_MARKING": "classification_marking",
    "EAR_MARKING": "classification_marking",
    "CAGE_CODE": "classification_marking",
    "DUNS_NUMBER": "classification_marking",
    "UEI": "classification_marking",
    "DOD_CONTRACT": "classification_marking",
    "GSA_CONTRACT": "classification_marking",

    # Education / FERPA
    "STUDENT_ID": "education",
    "TRANSCRIPT": "education",
    "ENROLLMENT_ID": "education",
    "FINANCIAL_AID_ID": "education",
    "SCHOOL_RECORD": "education",
    "GPA": "education",
    "DISCIPLINARY_RECORD": "education",
    "IEP_ID": "education",
    "TEACHER_ID": "education",
    "FERPA_DIRECTORY_INFO": "education",

    # Legal
    "CASE_NUMBER": "legal",
    "BAR_NUMBER": "legal",
    "COURT_ID": "legal",
    "PACER_ID": "legal",
    "INMATE_NUMBER": "legal",
    "PROBATION_ID": "legal",
    "ARREST_RECORD": "legal",
    "WARRANT_NUMBER": "legal",
    "JUDGMENT_ID": "legal",
    "LEGAL_HOLD_ID": "legal",

    # Vehicle & Transportation
    "REGISTRATION_NUMBER": "vehicle",
    "TITLE_NUMBER": "vehicle",
    "DOT_NUMBER": "vehicle",
    "MC_NUMBER": "vehicle",
    "VESSEL_ID": "vehicle",
    "AIRCRAFT_TAIL": "vehicle",
    "PILOT_LICENSE": "vehicle",
    "CDL_NUMBER": "vehicle",
    "TOLL_ACCOUNT": "vehicle",

    # Immigration
    "SEVIS_ID": "immigration",
    "TRAVEL_DOCUMENT_NUMBER": "immigration",
    "PETITION_NUMBER": "immigration",

    # Insurance
    "POLICY_NUMBER": "insurance",
    "CLAIM_NUMBER": "insurance",
    "AGENT_NUMBER": "insurance",
    "ADJUSTER_ID": "insurance",
    "NAIC_NUMBER": "insurance",
    "AUTO_POLICY_ID": "insurance",
    "HOME_POLICY_ID": "insurance",
    "LIFE_POLICY_ID": "insurance",
    "WORKERS_COMP_CLAIM": "insurance",
    "DISABILITY_CLAIM_ID": "insurance",

    # Real Estate
    "PARCEL_NUMBER": "real_estate",
    "DEED_NUMBER": "real_estate",
    "ESCROW_NUMBER": "real_estate",
    "MLS_NUMBER": "real_estate",
    "HOA_ACCOUNT": "real_estate",
    "TITLE_POLICY_NUMBER": "real_estate",
    "PROPERTY_TAX_ID": "real_estate",

    # Telecommunications
    "CARRIER_ACCOUNT": "telecom",
    "VOIP_ACCOUNT": "telecom",
    "CALLING_CARD_NUMBER": "telecom",
    "PORT_NUMBER": "telecom",

    # Biometric & Genetic
    "FINGERPRINT_TEMPLATE": "biometric",
    "FACE_TEMPLATE": "biometric",
    "IRIS_TEMPLATE": "biometric",
    "VOICE_PRINT": "biometric",
    "RETINAL_SCAN": "biometric",
    "PALM_PRINT": "biometric",
    "GAIT_SIGNATURE": "biometric",
    "DNA_SEQUENCE": "biometric",
    "GENETIC_MARKER": "biometric",
    "ANCESTRY_ID": "biometric",
    "BIOBANK_ID": "biometric",

    # Military
    "EDIPI": "military",
    "SERVICE_NUMBER": "military",
    "MILITARY_ID": "military",
    "VA_CLAIM_NUMBER": "military",
    "DD214_NUMBER": "military",
    "MOS_CODE": "military",
    "UNIT_IDENTIFICATION": "military",
    "SECURITY_BADGE_ID": "military",
    "SIPR_TOKEN": "military",
    "CAC_PIN": "military",

    # Sensitive Files
    "DOTENV_FILE": "sensitive_file",
    "KUBECONFIG": "sensitive_file",
    "SSH_CONFIG": "sensitive_file",
    "DOCKER_CONFIG": "sensitive_file",
    "NPM_RC": "sensitive_file",
    "PYPIRC": "sensitive_file",
    "AWS_CREDENTIALS_FILE": "sensitive_file",
    "NETRC": "sensitive_file",
    "HTPASSWD": "sensitive_file",
    "PGP_PRIVATE": "sensitive_file",
    "TERRAFORM_STATE": "sensitive_file",
    "ANSIBLE_VAULT": "sensitive_file",
    "CERTIFICATE_BUNDLE": "sensitive_file",
    "KEYSTORE": "sensitive_file",
    "WALLET_FILE": "sensitive_file",
    "HISTORY_FILE": "sensitive_file",
    "SHADOW_FILE": "sensitive_file",

    # Misc
    "UNIQUE_ID": "quasi_identifier",
}
